---
- hosts: basics
  roles:
  - fish
  - role: users 
    tags: users
  - weareinteractive.sudo
  - ssh-lockdown

- hosts: servers
  roles:
  - mosh
  - patrick-interactive

- hosts: docker
  roles:
  - geerlingguy.docker
  - docker-py

- hosts: macs
  vars:
    fish_package_user: patrick
    patrick_interactive_home: /Users/patrick
    patrick_interactive_group: staff
    patrick_interactive_package_user: patrick
    patrick_interactive_ssh_identity_agent: "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
  roles:
  - fish
  - patrick-interactive

- hosts: workmacs
  vars:
    fish_package_user: patrick.quinn-graham
    patrick_interactive_user: patrick.quinn-graham
    patrick_interactive_home: /Users/patrick.quinn-graham
    patrick_interactive_group: staff
    patrick_interactive_package_user: patrick.quinn-graham
    patrick_interactive_ssh_identity_agent: "~/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"
  roles:
  - fish
  - patrick-interactive

- hosts: sophieslinux
  vars:
    fish_package_user: sophie
    patrick_interactive_user: sophie
    patrick_interactive_home: /home/sophie
    patrick_interactive_group: sophie
    patrick_interactive_package_user: sophie
    patrick_interactive_ssh_identity_agent: "~/.1password/agent.sock"
  roles:
  - fish
  - patrick-interactive