users:
- name: sophie
  github_username: thissophie
  groups: sudo
  shell: /usr/bin/fish

sudo_defaults:
- defaults: env_reset
- defaults: secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
sudo_users:
- name: 'sophie'
  nopasswd: yes
purge_other_sudoers_files: no

time_zone: Australia/Sydney
domain: tamatekapua.com

# Git repos:
ansible_repo: https://github.com/thissophie/inventory.git
ansible_branch: main
ansible_repo_dir: servers
